### ISSUE TITLE
Send a SoapFault with HTTP status other than 500.

### ISSUE THREAD

**Issue by fozix** [koen-serneels/ws-proxy#3]
Hi Koen,

Thank you for this excellent tutorial on : https://www.javacodegeeks.com/2013/11/building-a-soap-webservices-proxy-module-using-spring-webservices.html

I'm using Interceptors to change the HTTP status in case of Exception thrown.
I was wandering why everytime an exception is thrown the client side get an HTTP status of 500. Is comming from spring implementation or from the proxy code.

Using for exemple a "ClientInterceptor" or an "HttpResponseInterceptor" to change the response status to 401 for exemple trigger a "WebServiceTransportException" and I'm getting 500 rather than 401 in HTTP status.

Is there a way to fix that please ?

Best regards.

**Comment by koen-serneels** [comment]
Hi @fozix. Exceptions should be translated to soap faults and these are to be returned with a 500 at the transport level per WS-I BP. This is disregarding the origin of the exception, either inside the wsproxy itself or upstream. Afaik it will be Spring that is creating the soap faults and also responsible for setting the http status code. 

Why do you want to change this to something else btw? No to jump conclusions but fiddling with the http status codes is not a good idea in terms of soap based webservices. If the upstream service is not standard then Spring will add the details of the response (which should include the status code) in the generated soap fault sent back to the client. If you need to be able to trigger on this in your client code then you could filter on this event at the wsproxy side (the 401 status code) and let it be translated to a  "customized" soap fault with extra details; eg using the code/subcode in case of soap1.2 or a custom payload in the detail part otherwise
